name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le dépôt
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installer les librairies Python (requirements.txt)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping pip install."
          fi

      # 4. Installer Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 5. Rendre le site (quarto render) en utilisant CE Python
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .
        env:
          QUARTO_PYTHON: python

      # 6. Publier sur GitHub Pages (branche gh-pages)
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
